"""Media engine — generates news articles and applies effects each tick."""

from dataclasses import dataclass, field
from typing import Any

from shared.schemas.agent_state import AgentState
from shared.schemas.simulation_state import SimulationState
from shared.types.aliases import TickNumber
from shared.utilities.deterministic_rng import DeterministicRNG

__all__ = ["NewsArticle", "process_media_tick"]


@dataclass
class NewsArticle:
    """A single news article generated by the media engine."""

    tick: int
    headline: str
    body: str
    category: str = "general"
    is_fake: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


def process_media_tick(
    world: SimulationState,
    tick_number: TickNumber | int,
    living_agents: list[AgentState],
    rng: DeterministicRNG,
) -> list[NewsArticle]:
    """Generate news articles and apply media effects for this tick.

    Examines world metrics (crime, unemployment, protests, economic health)
    and agent statistics to produce a small batch of news articles each
    tick. Articles are categorized as ``"economy"``, ``"crime"``,
    ``"politics"``, ``"social"``, or ``"general"``.

    Args:
        world: Current world state.
        tick_number: Current tick number.
        living_agents: List of living agents.
        rng: Deterministic RNG.

    Returns:
        A list of ``NewsArticle`` instances generated this tick.
    """
    articles: list[NewsArticle] = []

    if rng.random() > 0.35:
        return articles  # Not every tick generates news

    # --- Economy news ---
    if world.unemployment_rate > 0.15 and rng.random() < 0.5:
        articles.append(
            NewsArticle(
                tick=int(tick_number),
                headline=f"Unemployment hits {world.unemployment_rate:.0%}",
                body=f"Economic reports show unemployment rising to {world.unemployment_rate:.0%}, "
                f"driving fears of a recession as consumer confidence wavers.",
                category="economy",
                is_fake=rng.random() < 0.08,
            )
        )
    elif world.economy.inflation_rate > 0.05 and rng.random() < 0.4:
        articles.append(
            NewsArticle(
                tick=int(tick_number),
                headline=f"Inflation surges to {world.economy.inflation_rate:.1%}",
                body=f"Prices continue to climb as inflation reaches {world.economy.inflation_rate:.1%}, "
                f"putting pressure on household budgets across the nation.",
                category="economy",
                is_fake=False,
            )
        )

    # --- Crime news ---
    if world.crime_rate > 0.10 and rng.random() < 0.4:
        articles.append(
            NewsArticle(
                tick=int(tick_number),
                headline=f"Crime wave persists — rate at {world.crime_rate:.0%}",
                body=f"Authorities report ongoing criminal activity with a crime rate of "
                f"{world.crime_rate:.0%}, leaving residents on edge.",
                category="crime",
                is_fake=rng.random() < 0.05,
            )
        )

    # --- Protest / social unrest ---
    if world.protest_intensity > 0.3 and rng.random() < 0.5:
        articles.append(
            NewsArticle(
                tick=int(tick_number),
                headline=f"Protests intensify across the city",
                body=f"Civil unrest grows as protest intensity reaches "
                f"{world.protest_intensity:.0%}. Demonstrators demand change.",
                category="politics",
                is_fake=rng.random() < 0.10,
            )
        )

    # --- Food / water scarcity ---
    if world.food_availability < 0.4 and rng.random() < 0.4:
        articles.append(
            NewsArticle(
                tick=int(tick_number),
                headline=f"Food scarcity warning issued",
                body=f"Food availability has dropped to {world.food_availability:.0%}, "
                f"prompting concerns about malnutrition among vulnerable populations.",
                category="social",
                is_fake=False,
            )
        )

    # --- Community / feel-good (only when things are good) ---
    if (world.unemployment_rate < 0.08
            and world.crime_rate < 0.05
            and world.economic_health > 0.7
            and rng.random() < 0.3):
        articles.append(
            NewsArticle(
                tick=int(tick_number),
                headline=f"Community morale high as economy prospers",
                body=f"With low unemployment and strong economic health, "
                f"communities report rising satisfaction and optimism.",
                category="general",
                is_fake=False,
            )
        )

    return articles
