"""
Shared Constants Module
=======================

Provides configuration constants and thresholds.
"""

from shared.constants.defaults import (
    DEFAULT_POPULATION_SIZE,
    DEFAULT_SIMULATION_SEED,
    DEFAULT_TICK_RATE_MS,
    DEFAULT_MAX_TICKS,
    DEFAULT_AGENT_LIFESPAN_TICKS,
    DEFAULT_INITIAL_WEALTH,
    DEFAULT_AMBIGUITY_THRESHOLD,
    DEFAULT_DETERMINISTIC_WEIGHT,
    DEFAULT_GEMMA_WEIGHT,
    DEFAULT_LOG_LEVEL,
    DEFAULT_API_PORT,
    DEFAULT_FRONTEND_PORT,
    DEFAULT_VLLM_PORT,
    DEFAULT_VLLM_MODEL,
)
from shared.constants.thresholds import (
    AMBIGUITY_THRESHOLD_MIN,
    AMBIGUITY_THRESHOLD_MAX,
    CONFIDENCE_THRESHOLD_LOW,
    CONFIDENCE_THRESHOLD_MEDIUM,
    CONFIDENCE_THRESHOLD_HIGH,
    NEED_CRITICAL_THRESHOLD,
    NEED_SATISFIED_THRESHOLD,
    EMOTION_INTENSITY_LOW,
    EMOTION_INTENSITY_HIGH,
    WEALTH_POOR_THRESHOLD,
    WEALTH_WEALTHY_THRESHOLD,
    CRIME_RATE_HIGH_THRESHOLD,
    UNLUST_HIGH_THRESHOLD,
    POPULATION_GROWTH_RATE_MAX,
    INFLATION_RATE_TARGET,
    UNEMPLOYMENT_RATE_NATURAL,
)

__all__ = [
    "DEFAULT_POPULATION_SIZE",
    "DEFAULT_SIMULATION_SEED",
    "DEFAULT_TICK_RATE_MS",
    "DEFAULT_MAX_TICKS",
    "DEFAULT_AGENT_LIFESPAN_TICKS",
    "DEFAULT_INITIAL_WEALTH",
    "DEFAULT_AMBIGUITY_THRESHOLD",
    "DEFAULT_DETERMINISTIC_WEIGHT",
    "DEFAULT_GEMMA_WEIGHT",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_API_PORT",
    "DEFAULT_FRONTEND_PORT",
    "DEFAULT_VLLM_PORT",
    "DEFAULT_VLLM_MODEL",
    "AMBIGUITY_THRESHOLD_MIN",
    "AMBIGUITY_THRESHOLD_MAX",
    "CONFIDENCE_THRESHOLD_LOW",
    "CONFIDENCE_THRESHOLD_MEDIUM",
    "CONFIDENCE_THRESHOLD_HIGH",
    "NEED_CRITICAL_THRESHOLD",
    "NEED_SATISFIED_THRESHOLD",
    "EMOTION_INTENSITY_LOW",
    "EMOTION_INTENSITY_HIGH",
    "WEALTH_POOR_THRESHOLD",
    "WEALTH_WEALTHY_THRESHOLD",
    "CRIME_RATE_HIGH_THRESHOLD",
    "UNLUST_HIGH_THRESHOLD",
    "POPULATION_GROWTH_RATE_MAX",
    "INFLATION_RATE_TARGET",
    "UNEMPLOYMENT_RATE_NATURAL",
]
